services:
  postgres:
    image: postgres:15-alpine
    container_name: inventory-postgres
    environment:
      POSTGRES_USER: fortna_user
      POSTGRES_PASSWORD: fortna_password
      POSTGRES_DB: inventory_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U fortna_user -d inventory_db"]
      interval: 5s
      timeout: 5s
      retries: 10

  liquibase:
    image: liquibase/liquibase:4.24.0
    volumes:
      - ./database/changelog:/liquibase/changelog
    command: >
      --url=jdbc:postgresql://postgres:5432/inventory_db
      --username=fortna_user
      --password=fortna_password
      --changelog-file=db.changelog-master.yaml
      update
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis:7-alpine
    container_name: inventory-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: inventory-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/inventory_db
      SPRING_DATASOURCE_USERNAME: fortna_user
      SPRING_DATASOURCE_PASSWORD: fortna_password
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379
    depends_on:
      liquibase:
        condition: service_completed_successfully
      redis:
        condition: service_healthy